export const sampleSites = [
  {
    id: 'capital',
    label: 'Horizon',
    data: {
      templateId: '1',
      businessName: 'Horizon Partners',
      eyebrow: 'Strategic Capital Advisory',
      heroTitle: 'Transforming Complexity\nInto Clear\nMarket Advantage',
      heroP: 'Meridian Capital Advisory works with founders, family offices, and active investors who want clearer capital decisions, tighter opportunity review, and a steady outside perspective.',
      aboutH2: 'Selective Advice,\nClear Thinking',
      aboutP1: 'We support a focused set of clients on allocation, diligence, and long-horizon planning. The work is straightforward: understand the mandate, pressure-test the options, and help move capital with discipline.',
      aboutP2: 'Most clients come to us when they want fewer opinions, cleaner analysis, and someone who can sit between strategy and execution without turning every conversation into theater.',
      services: [
        { name: 'Capital Strategy', description: 'Portfolio direction, liquidity planning, and capital deployment framed around actual priorities instead of generic market commentary.' },
        { name: 'Opportunity Review', description: 'Practical diligence support on new deals, partnerships, and operating bets before time and attention get wasted.' },
        { name: 'Investor Advisory', description: 'Ongoing strategic support for investors and owner-operators who want a calm second chair on important decisions.' },
      ],
      email: 'info@meridiancapitaladvisory.com',
      phone: '(949) 555-0142',
      address: '450 Newport Center Dr, Newport Beach, CA 92660',
      logoUrl: '',
      domain: 'meridiancapitaladvisory.com',
      contactBlurb: 'If you are thinking through allocation, an acquisition, or a broader strategic shift, send a note and we can compare priorities.',
      colors: {
        accent: '#b99341',
      },
      stats: [
        ['15+', 'Years Advising'],
        ['$240M+', 'Capital Reviewed'],
        ['Limited', 'Client Roster'],
      ],
    },
  },
  {
    id: 'advisory',
    label: 'Lumina',
    data: {
      templateId: '2',
      businessName: 'Lumina Consulting',
      eyebrow: 'Enterprise Advisory',
      heroTitle: 'Clarity Amidst\nComplexity',
      heroP: 'North Coast Strategic Partners advises founders, investors, and small leadership teams on growth planning, strategic positioning, and decision support when the next move carries real weight.',
      aboutH2: 'Senior Perspective,\nPractical Execution',
      aboutP1: 'We are brought in when leaders want thoughtful outside input without adding noise to the room. That usually means clarifying the decision, tightening the plan, and helping the team move with more conviction.',
      aboutP2: 'Our work is intentionally narrow and hands-on, with a bias toward direct analysis, honest tradeoffs, and materials that can actually be used by operators and investors.',
      services: [
        { name: 'Strategic Planning', description: 'Focused planning engagements for teams that need sharper priorities, cleaner positioning, and a workable operating direction.' },
        { name: 'Decision Support', description: 'Support around hires, market moves, partnerships, and internal strategy when the downside of a rushed call is expensive.' },
        { name: 'Leadership Advisory', description: 'Ongoing counsel for founders and principals who want a trusted outside view without building a bigger internal layer.' },
      ],
      email: 'team@northcoaststrategic.com',
      phone: '(714) 555-0183',
      address: '488 Harbor Blvd, Costa Mesa, CA 92627',
      logoUrl: '',
      domain: 'northcoaststrategic.com',
      contactBlurb: 'Share what you are working through, and we can tell you quickly whether we are the right fit for the conversation.',
      colors: {
        accent: '#0f4c81',
      },
      stats: [
        ['80+', 'Advisory Engagements'],
        ['Founder', 'Led Mandates'],
        ['24 hrs', 'Initial Response'],
      ],
    },
  },
  {
    id: 'investment',
    label: 'Investment Office',
    data: {
      templateId: '3',
      businessName: 'Summit Ridge Investment Office',
      eyebrow: 'Acquisitions & Asset Strategy',
      heroTitle: 'Sharper Views\nOn Assets,\nOperators,\nAnd Risk',
      heroP: 'Summit Ridge Investment Office helps active buyers and operators evaluate opportunities, frame risk, and improve decision quality across acquisitions, portfolio assets, and operating plans.',
      aboutH2: 'High Conviction,\nLow Drama',
      aboutP1: 'We work with investors who need faster synthesis and cleaner underwriting without losing the nuance behind the decision. The goal is not more paperwork. It is better judgment.',
      aboutP2: 'Whether the issue is a new acquisition, a wobbly asset, or an operating question inside the portfolio, we help teams focus on what matters and ignore what does not.',
      services: [
        { name: 'Acquisition Review', description: 'Underwriting support, opportunity framing, and decision memos for buyers who want clearer go or no-go calls.' },
        { name: 'Asset Strategy', description: 'Portfolio-level thinking around positioning, performance, and capital priorities for existing holdings.' },
        { name: 'Operating Assessment', description: 'Outside review for assets or teams that need a more disciplined read on execution, margin, and risk.' },
      ],
      email: 'partners@summitridgeoffice.com',
      phone: '(562) 555-0124',
      address: '910 Industry Way, Long Beach, CA 90813',
      logoUrl: '',
      domain: 'summitridgeoffice.com',
      contactBlurb: 'If you are evaluating an asset, pressure-testing a plan, or sorting through an operating issue, send over the outline and we will take a look.',
      colors: {
        accent: '#2f5d3a',
        gold: '#c89d3c',
      },
      stats: [
        ['120+', 'Deals Reviewed'],
        ['$500M+', 'Asset Value Touched'],
        ['Multi-Market', 'Coverage'],
      ],
    },
  },
  {
    id: 'family-office',
    label: 'Private Office',
    data: {
      templateId: '4',
      businessName: 'Harbor Row Advisory Office',
      eyebrow: 'Private Office & Family Advisory',
      heroTitle: 'Private Guidance\nFor Significant\nDecisions',
      heroP: 'Harbor Row Advisory Office supports families, principals, and closely held businesses with strategic planning, succession conversations, and high-trust advisory work.',
      aboutH2: 'Quiet Support,\nSerious Judgment',
      aboutP1: 'We work best in situations that require discretion, patience, and clear thinking across multiple stakeholders. That may involve ownership planning, family conversations, or long-range decision support.',
      aboutP2: 'The role is simple: help organize the issues, clarify the options, and keep important decisions moving without unnecessary friction or performative complexity.',
      services: [
        { name: 'Strategic Counsel', description: 'Private advisory support for principals and leadership groups navigating sensitive or high-consequence decisions.' },
        { name: 'Succession Planning', description: 'Thoughtful planning around ownership transition, continuity, and long-term stewardship.' },
        { name: 'Family Office Support', description: 'Advisory work across planning, structure, and coordination when priorities span business, family, and capital.' },
      ],
      email: 'office@harborrowadvisory.com',
      phone: '(310) 555-0176',
      address: '210 Wilshire Blvd, Santa Monica, CA 90401',
      logoUrl: '',
      domain: 'harborrowadvisory.com',
      contactBlurb: 'If the conversation is sensitive, high-stakes, or simply easier to handle with a steady outside advisor, feel free to reach out.',
      colors: {
        accent: '#7d2535',
      },
      stats: [
        ['Private', 'By Referral'],
        ['Long Horizon', 'Planning Focus'],
        ['Direct', 'Principal Access'],
      ],
    },
  },
  {
    id: 'template-5-preview',
    label: 'Nexus',
    data: {
      templateId: '5',
      businessName: 'Nexus Strategy',
      eyebrow: 'Enterprise Systems Advisory',
      heroTitle: 'Architecting\nEnterprise\nSystems',
      heroP: 'Anchor Point Advisory helps operators, consultants, and small firms sharpen positioning, tighten messaging, and prepare for the next growth or capital conversation with less noise.',
      aboutH2: 'Practical Direction,\nCleaner Messaging',
      aboutP1: 'We work with businesses that need clearer language, tighter public presentation, and a more coherent way to explain where they are headed.',
      aboutP2: 'The goal is simple: make the business easier to understand, easier to trust, and easier to move forward with.',
      services: [
        { name: 'Positioning Review', description: 'Audit the current message, offer, and homepage narrative to identify where the story is unclear or underselling the business.' },
        { name: 'Growth Planning', description: 'Clarify priorities, decision paths, and communication for teams entering a new market, offer, or operating stage.' },
        { name: 'Capital Readiness', description: 'Strengthen the way the business presents itself to lenders, partners, or outside capital before those conversations start.' },
      ],
      email: 'hello@anchorpointadvisory.com',
      phone: '(949) 555-0115',
      address: '400 Spectrum Center Dr, Irvine, CA 92618',
      logoUrl: '',
      domain: 'anchorpointadvisory.com',
      contactBlurb: 'Send a quick note with what feels unclear, undersold, or high-stakes right now, and we will reply with a practical next step.',
      colors: {
        accent: '#2d5f73',
      },
      stats: [
        ['Positioning', 'Homepage & Offer Clarity'],
        ['Growth', 'Priority Setting'],
        ['Readiness', 'Lender & Partner Support'],
      ],
    },
  },
  {
    id: 'template-6-preview',
    label: 'Aura',
    data: {
      templateId: '6',
      businessName: 'Aura Partners',
      eyebrow: 'Private Advisory',
      heroTitle: 'Refined\nIntelligence',
      heroP: 'Stone Harbor Counsel advises founders and leadership teams on growth decisions, business clarity, and strategic communication when the next move carries real weight.',
      aboutH2: 'High Trust,\nLow Theater',
      aboutP1: 'We are brought in when operators want sharper outside thinking without adding more presentation, process, or internal drag.',
      aboutP2: 'That usually means helping the team clarify the issue, cut down the noise, and move with more confidence.',
      services: [
        { name: 'Decision Support', description: 'Outside perspective on hiring, partnerships, market moves, and strategic calls where the downside of a rushed answer is expensive.' },
        { name: 'Narrative Refinement', description: 'Tighten the way the business explains itself across the homepage, pitch materials, and core offer language.' },
        { name: 'Operating Focus', description: 'Help leadership teams reduce drift, clarify priorities, and put cleaner communication behind the current plan.' },
      ],
      email: 'team@stoneharborcounsel.com',
      phone: '(310) 555-0161',
      address: '100 Wilshire Blvd, Santa Monica, CA 90401',
      logoUrl: '',
      domain: 'stoneharborcounsel.com',
      contactBlurb: 'Share the decision, pressure point, or messy draft you are working through, and we can tell you quickly where support would help.',
      colors: {
        accent: '#355b4f',
      },
      stats: [
        ['Advice', 'Senior Outside View'],
        ['Messaging', 'Clearer Public Story'],
        ['Execution', 'Practical Recommendations'],
      ],
    },
  },
  {
    id: 'template-7-preview',
    label: 'Veritas',
    data: {
      templateId: '7',
      businessName: 'Veritas Group',
      eyebrow: 'Generational Capital Advisory',
      heroTitle: 'Enduring Strategy\nFor Generational\nCapital',
      heroP: 'Northline Strategy Office supports founders, owner-operators, and small investment groups with positioning, opportunity review, and direct strategic support.',
      aboutH2: 'Clear Signals,\nBetter Decisions',
      aboutP1: 'We help clients simplify how the business shows up, pressure-test the next move, and replace vague growth plans with decisions that can actually be acted on.',
      aboutP2: 'The work stays narrow and useful: clear language, direct recommendations, and support that respects the pace of the business.',
      services: [
        { name: 'Strategic Positioning', description: 'Clarify the offer, sharpen the story, and align public-facing messaging with the actual quality of the business.' },
        { name: 'Opportunity Review', description: 'Evaluate new deals, partnerships, and operating moves with a tighter lens on upside, downside, and fit.' },
        { name: 'Advisory Retainers', description: 'Ongoing support for operators who want a steady outside perspective without building a larger internal layer.' },
      ],
      email: 'hello@northlinestrategy.com',
      phone: '(714) 555-0129',
      address: '695 Town Center Dr, Costa Mesa, CA 92626',
      logoUrl: '',
      domain: 'northlinestrategy.com',
      contactBlurb: 'If you are trying to improve positioning, evaluate a move, or bring more discipline to the next phase, send over the outline.',
      colors: {
        accent: '#0f4c81',
      },
      stats: [
        ['Scope', 'Focused Strategic Support'],
        ['Fit', 'Founders & Operators'],
        ['Pace', 'Fast, Direct Feedback'],
      ],
    },
  },
  {
    id: 'template-8-preview',
    label: 'Onyx',
    data: {
      templateId: '8',
      businessName: 'Onyx Advisory',
      eyebrow: 'Restricted Access Advisory',
      heroTitle: 'Uncompromising\nExcellence',
      heroP: 'Crestline Advisory Group helps founder-led businesses and active investors improve decision quality, sharpen communication, and navigate growth with more structure.',
      aboutH2: 'Disciplined Thinking,\nPractical Output',
      aboutP1: 'We support teams that need cleaner strategic framing, tighter diligence, and a more credible public-facing story before the next important conversation.',
      aboutP2: 'That might involve a homepage, a deal memo, a planning sprint, or simply a better way to explain what the business is doing and why it matters.',
      services: [
        { name: 'Growth Strategy', description: 'Frame priorities, simplify the path forward, and give leadership teams a clearer operating narrative.' },
        { name: 'Diligence Support', description: 'Review opportunities, assumptions, and risk with a practical operator-investor lens.' },
        { name: 'Credibility Build', description: 'Improve the way the business presents itself online and in key materials so the next room is easier to enter.' },
      ],
      email: 'partners@crestlineadvisory.com',
      phone: '(562) 555-0188',
      address: '3780 Kilroy Airport Way, Long Beach, CA 90806',
      logoUrl: '',
      domain: 'crestlineadvisory.com',
      contactBlurb: 'Tell us what you are evaluating or trying to strengthen, and we will reply with a focused recommendation on where to start.',
      colors: {
        accent: '#6a4b9e',
      },
      stats: [
        ['Strategy', 'Priorities & Positioning'],
        ['Diligence', 'Risk & Opportunity Review'],
        ['Credibility', 'Public-Facing Clarity'],
      ],
    },
  },
  {
    id: 'template-9-preview',
    label: 'Equinox',
    data: {
      templateId: '9',
      businessName: 'Equinox Partners',
    },
  },
  {
    id: 'template-10-preview',
    label: 'Vanguard',
    data: {
      templateId: '10',
      businessName: 'Vanguard Network',
    },
  },
]
