import {
  LEGAL_CONSENT_LABEL_TEXT,
  LEGAL_CONSENT_PARTS,
} from '../legal/legalConfig';

export const SALES_ASSISTANT_QUESTION_STEPS = [
  {
    id: 'q01_role_type',
    kicker: 'Business Picture',
    title: 'Which best describes you?',
    description: 'Choose the option that best matches how you operate today.',
    fields: [
      {
        name: 'roleType',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'Sandler agent',
          'Sandler sub-agent',
          'Agent with sub-agents',
          'Agency owner / sales leader',
          'Newer agent building my workflow',
        ],
      },
    ],
  },
  {
    id: 'q02_business_structure',
    kicker: 'Business Picture',
    title: 'What is your business structure?',
    description: 'This helps frame how complex the workflow needs to be.',
    fields: [
      {
        name: 'businessStructure',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'Solo independent agent',
          'Independent agent with contractors',
          'Small agency team',
          'Agency with sub-agents',
          'Other',
        ],
      },
    ],
  },
  {
    id: 'q03_main_territory',
    kicker: 'Business Picture',
    title: 'What territory do you mainly work in?',
    description: 'We want the operational footprint, not just a mailing address.',
    fields: [
      {
        name: 'mainTerritory',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: ['Local / one metro', 'Regional', 'Multi-state', 'National', 'Mixed'],
      },
    ],
  },
  {
    id: 'q04_top_services',
    kicker: 'Business Picture',
    title: 'What types of services do you sell most often?',
    description: 'Pick the lane that feels closest to your current book of business.',
    fields: [
      {
        name: 'topServices',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'Internet',
          'UC / phones',
          'Mobility / wireless',
          'Cloud / IT services',
          'Security / surveillance',
          'SD-WAN / network',
          'A mix of several',
        ],
      },
    ],
  },
  {
    id: 'q05_biggest_time_sink',
    kicker: 'Workflow Reality',
    title: 'What takes up the biggest part of your week?',
    description: 'Choose the area that creates the most drag in practice.',
    fields: [
      {
        name: 'biggestTimeSink',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'Internet quoting',
          'UC / phone quoting',
          'Provider research',
          'Commission tracking',
          'Contracts and paperwork',
          'Prospect follow-up and admin',
          'A mix of everything',
        ],
      },
    ],
  },
  {
    id: 'q06_active_opportunity_volume',
    kicker: 'Workflow Reality',
    title: 'How many active opportunities do you usually have at once?',
    description: 'Rough ranges are fine.',
    fields: [
      {
        name: 'activeOpportunityVolume',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: ['1-5', '6-15', '16-30', '31-60', '60+'],
      },
    ],
  },
  {
    id: 'q07_weekly_quote_volume',
    kicker: 'Workflow Reality',
    title: 'How many quotes do you usually touch in a normal week?',
    description: 'We are looking for the typical workload, not the best week.',
    fields: [
      {
        name: 'weeklyQuoteVolume',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: ['0-2', '3-5', '6-10', '11-20', '20+'],
      },
    ],
  },
  {
    id: 'q08_recurring_workflow_tasks',
    kicker: 'Workflow Reality',
    title: 'Which of these do you do at least a few times a month?',
    description: 'Select all that apply.',
    fields: [
      {
        name: 'recurringWorkflowTasks',
        label: 'Select all that apply',
        type: 'checkbox',
        required: true,
        options: [
          'Build internet quotes from SCOUT or carrier pricing',
          'Build UC quotes across providers',
          'Rework quotes after client feedback',
          'Pull commission statements',
          'Send paperwork for e-signature',
          'Create or rename prospect folders',
          'Check CRM / contact records',
          'Monitor provider deal or quote status',
        ],
      },
    ],
  },
  {
    id: 'q09_opportunity_first_step',
    kicker: 'Workflow Reality',
    title: 'When a new opportunity comes in, what usually happens first?',
    description: 'Pick the first real behavior, even if it is not ideal.',
    fields: [
      {
        name: 'opportunityFirstStep',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'I open SCOUT or provider tools',
          'I pull an old quote and edit it',
          'I gather bills and compare options',
          'I text/email myself notes and deal with it later',
          'It depends on the provider',
        ],
      },
    ],
  },
  {
    id: 'q10_current_stall_point',
    kicker: 'Workflow Reality',
    title: 'Where do opportunities most often stall right now?',
    description: 'This points to where the assistant should create leverage first.',
    fields: [
      {
        name: 'currentStallPoint',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'Waiting on quote inputs',
          'Waiting on provider portal work',
          'Waiting on me to follow up',
          'Waiting on paperwork or signatures',
          'Waiting on internal organization',
          'It varies too much',
        ],
      },
    ],
  },
  {
    id: 'q11_quote_delay_cause',
    kicker: 'Workflow Reality',
    title: 'What usually causes the most delay when building a quote?',
    description: 'Choose the slowdown that shows up most often.',
    fields: [
      {
        name: 'quoteDelayCause',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'Getting the right client info',
          'Looking up pricing',
          'Logging into portals',
          'Reworking old documents',
          'Waiting on carrier responses',
          'Too many moving pieces',
        ],
      },
    ],
  },
  {
    id: 'q12_multi_portal_frequency',
    kicker: 'Workflow Reality',
    title: 'How often do you need to touch more than one vendor or portal for a single opportunity?',
    description: 'We are mapping how cross-system the work really is.',
    fields: [
      {
        name: 'multiPortalFrequency',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: ['Almost every time', 'Often', 'Sometimes', 'Rarely'],
      },
    ],
  },
  {
    id: 'q13_active_systems',
    kicker: 'Systems and File Flow',
    title: 'Which systems do you actively use today?',
    description: 'Select all that apply.',
    fields: [
      {
        name: 'activeSystems',
        label: 'Select all that apply',
        type: 'checkbox',
        required: true,
        options: [
          'Microsoft 365 / Outlook',
          'Google Workspace',
          'Adobe Acrobat / e-sign',
          'HubSpot',
          'OneDrive',
          'Google Drive / Dropbox',
          'SandlerPortal',
          'SCOUT',
          'RingCentral Partner Portal',
          'Broadvoice portal',
        ],
      },
    ],
  },
  {
    id: 'q14_mandatory_systems',
    kicker: 'Systems and File Flow',
    title: 'Which systems are mandatory for your day-to-day work?',
    description: 'Select all that apply.',
    fields: [
      {
        name: 'mandatorySystems',
        label: 'Select all that apply',
        type: 'checkbox',
        required: true,
        options: [
          'SandlerPortal',
          'SCOUT',
          'Microsoft 365 / Outlook',
          'Google Workspace',
          'Adobe Acrobat / e-sign',
          'HubSpot',
          'RingCentral Partner Portal',
          'Broadvoice portal',
        ],
      },
    ],
  },
  {
    id: 'q15_priority_accounts',
    kicker: 'Systems and File Flow',
    title: 'Which accounts should the assistant be prepared to work with first?',
    description: 'Select all that apply.',
    fields: [
      {
        name: 'priorityAccounts',
        label: 'Select all that apply',
        type: 'checkbox',
        required: true,
        options: [
          'Microsoft',
          'Google',
          'Adobe',
          'SandlerPortal',
          'SCOUT',
          'RingCentral',
          'Broadvoice',
          'HubSpot',
        ],
      },
    ],
  },
  {
    id: 'q16_browser_portal_dependence',
    kicker: 'Systems and File Flow',
    title: 'How much of your week still lives inside browser portals?',
    description: 'This helps us judge how much portal work needs to be absorbed.',
    fields: [
      {
        name: 'browserPortalDependence',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'Mostly browser portals',
          'A mix of portals and clean systems',
          'Mostly clean systems already',
          'I am not sure',
        ],
      },
    ],
  },
  {
    id: 'q17_file_storage_home',
    kicker: 'Systems and File Flow',
    title: 'Where do your prospect and quote files usually live?',
    description: 'Pick the place files most often end up.',
    fields: [
      {
        name: 'fileStorageHome',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: ['OneDrive', 'Google Drive', 'Dropbox', 'Local folders', 'Mixed / messy right now'],
      },
    ],
  },
  {
    id: 'q18_deal_notes_home',
    kicker: 'Systems and File Flow',
    title: 'Where do you usually keep notes on deals?',
    description: 'Choose the place you rely on most often, even if it is inconsistent.',
    fields: [
      {
        name: 'dealNotesHome',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'In my head',
          'Text messages',
          'Email threads',
          'CRM notes',
          'Prospect folders',
          'Paper notes',
          'Mixed everywhere',
        ],
      },
    ],
  },
  {
    id: 'q19_folder_organization',
    kicker: 'Systems and File Flow',
    title: 'How organized are your prospect folders and files right now?',
    description: 'Answer based on whether you trust the structure when work gets busy.',
    fields: [
      {
        name: 'folderOrganization',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'Very organized',
          'Good enough but inconsistent',
          'Messy but workable',
          'Hard to trust',
          'I do not really have a system',
        ],
      },
    ],
  },
  {
    id: 'q20_quote_work_focus',
    kicker: 'Quote Ops and Commissions',
    title: 'What kinds of quote work matter most right now?',
    description: 'Pick the quote pattern that best reflects the current moment.',
    fields: [
      {
        name: 'quoteWorkFocus',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'Internet only',
          'UC / phones only',
          'Both internet and UC',
          'Mostly revisions and comparisons',
          'A mix depending on the week',
        ],
      },
    ],
  },
  {
    id: 'q21_paperwork_pattern',
    kicker: 'Quote Ops and Commissions',
    title: 'When paperwork needs to go out, what usually happens?',
    description: 'Choose the pattern that shows up most often.',
    fields: [
      {
        name: 'paperworkPattern',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'I prepare and send it myself',
          'I prepare it but delay sending',
          'I reuse old files and adjust them',
          'I wait until the client asks again',
          'It depends on the provider',
        ],
      },
    ],
  },
  {
    id: 'q22_commission_tracking',
    kicker: 'Quote Ops and Commissions',
    title: 'How are commissions tracked today?',
    description: 'Pick the process that is closest to reality.',
    fields: [
      {
        name: 'commissionTracking',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'I check them manually when I remember',
          'I review them monthly',
          'I export and compare statements',
          'I mostly ignore them until something looks wrong',
          'Someone else helps me',
        ],
      },
    ],
  },
  {
    id: 'q23_required_approvals',
    kicker: 'Trust Boundaries',
    title: 'What should always require your approval?',
    description: 'Select all that apply.',
    fields: [
      {
        name: 'requiredApprovals',
        label: 'Select all that apply',
        type: 'checkbox',
        required: true,
        options: [
          'Client-facing sends',
          'CRM updates',
          'Portal submissions',
          'Contract / e-sign actions',
          'External messages of any kind',
        ],
      },
    ],
  },
  {
    id: 'q24_immediate_value',
    kicker: 'Trust Boundaries',
    title: 'What would make this assistant feel immediately useful?',
    description: 'Choose the outcome you would want to feel right away.',
    fields: [
      {
        name: 'immediateValue',
        label: 'Select one',
        type: 'radio',
        required: true,
        options: [
          'Faster quoting',
          'Better follow-up',
          'Less portal chaos',
          'Better commission visibility',
          'Cleaner organization',
          'Less mental overhead',
        ],
      },
    ],
  },
];

export const SALES_ASSISTANT_CONTACT_STEP = {
  id: 'contact_info',
  kicker: 'Contact Info',
  title: 'Where should we send follow-up?',
  description: 'We will use this to review your intake and reach out about next steps.',
  fields: [
    {
      name: 'fullName',
      label: 'Full Name',
      placeholder: 'Taylor Morgan',
      type: 'text',
      required: true,
    },
    {
      name: 'businessName',
      label: 'Agency / Business Name',
      placeholder: 'Morgan Telecom Advisory',
      type: 'text',
      required: true,
    },
    {
      name: 'contactEmail',
      label: 'Email',
      placeholder: 'taylor@example.com',
      type: 'email',
      required: true,
    },
    {
      name: 'phoneNumber',
      label: 'Phone Number',
      placeholder: '+1 (555) 000-0000',
      type: 'tel',
      required: true,
    },
    {
      name: 'legalAccepted',
      label: LEGAL_CONSENT_LABEL_TEXT,
      labelParts: LEGAL_CONSENT_PARTS,
      type: 'consent',
      required: true,
      errorMessage: 'You must accept the Privacy Policy and Terms of Service to continue.',
    },
  ],
};

export const SALES_ASSISTANT_INTAKE_STEPS = [
  ...SALES_ASSISTANT_QUESTION_STEPS,
  SALES_ASSISTANT_CONTACT_STEP,
];
